alias ls='eza -F'
alias ll='ls -l'
alias l='ll -a'
alias la='ls -a'
alias rm='rm -i'
alias cat=bat
forgit_checkout_commit=gcoc
alias gpom='git push origin master'
alias gadd='git commit -a --amend --no-edit'
